<VerificationScreen>:
    name: 'verification'
    BoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: 'Profile'
            left_action_items: [['menu', lambda x: app.root.toggle_nav_drawer()]]
            pos_hint: {"top": 1}

        BoxLayout:
            orientation: 'vertical'
            padding: dp(20)
            spacing: dp(20)

            Widget:  # Spacer to push content down
                size_hint_y: 1

            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                padding: dp(10)
                spacing: dp(5)
                canvas.before:
                    Color:
                        rgba: root.background_primary  # Dynamic background color
                    Line:
                        width: 2
                        rectangle: (self.x, self.y, self.width, self.height)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20,]

                MDLabel:
                    text: 'Enter Verification Code'
                    halign: 'center'
                    font_style: 'H5'
                    size_hint_y: None
                    height: self.texture_size[1] + dp(10)
                    theme_text_color: 'Custom'
                    text_color: root.label_fontprimary

                MDTextField:
                    id: verification_input
                    hint_text: "Verification Code"
                    size_hint_y: None
                    height: dp(40)
                    pos_hint: {"center_x": 0.5}
                    halign: 'center'
                    text_color_normal: root.textfield_fontprimary  # Set text color dynamically
                    text_color_focus: root.textfield_fontprimary  # Set text color dynamically

                MDRaisedButton:
                    text: 'VERIFY'
                    size_hint_y: None
                    height: dp(48)
                    size_hint_x: 0.5
                    pos_hint: {"center_x": 0.5}  # Center the button horizontally
                    on_release: root.submit_verification(verification_input.text)
                    text_color: root.button_fontprimary  # Dynamic font color for button
                    on_press: self.md_bg_color = root.button_pressed  # Change background color on press

            Widget:  # Spacer to push content up
                size_hint_y: 1
