# This file defines the main layout and screen management for the application.

MDNavigationLayout:
    MDNavigationDrawer:
        id: nav_drawer
        ContentNavigationDrawer:
            id: content_drawer
            screen_manager: screen_manager  # Reference the main screen manager
            nav_drawer: nav_drawer  # Reference this navigation drawer

    MDNavigationDrawer:
        id: settings_right_nav_drawer  # Updated ID for the settings right navigation drawer
        anchor: 'right'  # Set the anchor to the right side
        SettingsRightNavigationDrawer:
            id: right_content_drawer
            screen_manager: screen_manager  # Reference the main screen manager
            nav_drawer: settings_right_nav_drawer  # Reference this navigation drawer

    ScreenManager:
        id: screen_manager
        HomeScreen:  # Add HomeScreen to the screen manager
        ProfileScreen:  # Add ProfileScreen to the screen manager
        StickHandScreen:  # Add StickHandScreen to the screen manager
        ForwardScreen:  # Add ForwardScreen to the screen manager
        DefenseScreen:  # Add DefenseScreen to the screen manager
        GoalieScreen:  # Add GoalieScreen to the screen manager
        CompetitiveScreen:  # Add CompetitiveScreen to the screen manager
        EmailScreen:  # Add EmailScreen to the screen manager
        VerificationScreen:  # Add VerificationScreen to the screen manager
        SettingsScreen:  # Add SettingsScreen to the screen manager
        Screen1:  # Add Screen1 to the screen manager
        Screen2:  # Add Screen2 to the screen manager
        EventScreen:  # Add EventScreen to the screen manager
