# home/home.kv
# This file defines the layout for the HomeScreen.

<HomeScreen>:
    name: 'home'  # Set the name of the screen
    BoxLayout:
        orientation: 'vertical'  # Set the orientation to vertical
        padding: dp(20)  # Set padding
        spacing: dp(20)  # Set spacing
        MDLabel:
            text: "Home Screen"  # Text for the home screen
            halign: 'center'  # Center the label horizontally
