<HomeScreen>:
    name: 'home'
    BoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Home"
            left_action_items: [["menu", lambda x: app.root.ids.nav_drawer.set_state("open")]]
        MDLabel:
            text: "Welcome to the Home Screen"
            halign: 'center'
        MDRaisedButton:
            text: "Go to Profile"
            pos_hint: {"center_x": .5}
            on_release: app.root.ids.screen_manager.current = 'profile'
