<ProfileScreen>:
    name: 'profile'
    BoxLayout:
        orientation: 'vertical'
        padding: dp(20)
        spacing: dp(10)

        MDLabel:
            text: "PROFILE"
            font_style: "H5"
            halign: "center"
            size_hint_y: None
            height: self.texture_size[1]

        MDCard:
            orientation: 'vertical'
            padding: dp(20)
            spacing: dp(10)
            size_hint: None, None
            size: dp(300), dp(400)
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            MDLabel:
                text: "Position"
                font_style: "H6"
                halign: "center"
                size_hint_y: None
                height: self.texture_size[1]

            BoxLayout:
                orientation: 'vertical'
                spacing: dp(20)  # Increased spacing

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDLabel:
                        text: "Forward"
                        font_style: "H6"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDCheckbox:
                        id: forward_left_wing_chk
                        group: 'forward'
                        on_active: root.update_forward(self, 'left_wing')

                    MDLabel:
                        text: "Left Wing"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDCheckbox:
                        id: forward_center_chk
                        group: 'forward'
                        on_active: root.update_forward(self, 'center')

                    MDLabel:
                        text: "Center"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDCheckbox:
                        id: forward_right_wing_chk
                        group: 'forward'
                        on_active: root.update_forward(self, 'right_wing')

                    MDLabel:
                        text: "Right Wing"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDLabel:
                        text: "Defense"
                        font_style: "H6"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDCheckbox:
                        id: defense_left_chk
                        group: 'defense'
                        on_active: root.update_defense(self, 'left')

                    MDLabel:
                        text: "Left Defense"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDCheckbox:
                        id: defense_right_chk
                        group: 'defense'
                        on_active: root.update_defense(self, 'right')

                    MDLabel:
                        text: "Right Defense"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                BoxLayout:
                    orientation: 'horizontal'
                    spacing: dp(10)

                    MDLabel:
                        text: "Goalie"
                        font_style: "H6"
                        halign: "left"
                        size_hint_y: None
                        height: self.texture_size[1]

                    MDCheckbox:
                        id: goalie_chk
                        on_active: root.update_goalie(self, 'goalie')

        MDRaisedButton:
            text: "Save Profile"
            pos_hint: {'center_x': 0.5}
            on_release: root.save_profile()
