<ProfileScreen>:
    name: 'profile'
    BoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: 'Profile'
            left_action_items: [['menu', lambda x: app.root.toggle_nav_drawer()]]
            pos_hint: {"top": 1}

        BoxLayout:
            orientation: 'vertical'
            padding: dp(20)
            spacing: dp(20)

            Widget:  # Spacer to push content down
                size_hint_y: 1

            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                padding: dp(10)
                spacing: dp(5)
                canvas.before:
                    Color:
                        rgba: root.background_primary  # Dynamic background color
                    Line:
                        width: 2
                        rectangle: (self.x, self.y, self.width, self.height)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20,]

                MDLabel:
                    text: 'Forward'
                    halign: 'center'
                    font_style: 'H5'
                    size_hint_y: None
                    height: self.texture_size[1] + dp(10)
                    theme_text_color: 'Custom'
                    text_color: root.label_fontprimary

                GridLayout:
                    cols: 2
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height

                    MDCheckbox:
                        id: left_wing_checkbox
                        group: 'forward'
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Left Wing"
                        halign: 'right'
                        valign: 'middle'

                    MDCheckbox:
                        id: center_checkbox
                        group: 'forward'
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Center"
                        halign: 'right'
                        valign: 'middle'

                    MDCheckbox:
                        id: right_wing_checkbox
                        group: 'forward'
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Right Wing"
                        halign: 'right'
                        valign: 'middle'

                MDLabel:
                    text: 'Defense'
                    halign: 'center'
                    font_style: 'H5'
                    size_hint_y: None
                    height: self.texture_size[1] + dp(10)
                    theme_text_color: 'Custom'
                    text_color: root.label_fontprimary

                GridLayout:
                    cols: 2
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height

                    MDCheckbox:
                        id: left_defense_checkbox
                        group: 'defense'
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Left Defense"
                        halign: 'right'
                        valign: 'middle'

                    MDCheckbox:
                        id: right_defense_checkbox
                        group: 'defense'
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Right Defense"
                        halign: 'right'
                        valign: 'middle'

                MDLabel:
                    text: 'Hand'
                    halign: 'center'
                    font_style: 'H5'
                    size_hint_y: None
                    height: self.texture_size[1] + dp(10)
                    theme_text_color: 'Custom'
                    text_color: root.label_fontprimary

                GridLayout:
                    cols: 2
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height

                    MDCheckbox:
                        id: left_hand_checkbox
                        group: 'hand'
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Left Hand"
                        halign: 'right'
                        valign: 'middle'

                    MDCheckbox:
                        id: right_hand_checkbox
                        group: 'hand'
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Right Hand"
                        halign: 'right'
                        valign: 'middle'

                MDLabel:
                    text: 'Goalie'
                    halign: 'center'
                    font_style: 'H5'
                    size_hint_y: None
                    height: self.texture_size[1] + dp(10)
                    theme_text_color: 'Custom'
                    text_color: root.label_fontprimary

                GridLayout:
                    cols: 1
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height

                    MDCheckbox:
                        id: goalie_checkbox
                        size_hint: None, None
                        size: dp(48), dp(48)
                        on_active: root.save_user_profile()

                    MDLabel:
                        text: "Goalie"
                        halign: 'right'
                        valign: 'middle'

            Widget:  # Spacer to push content up
                size_hint_y: 1
