<ProfileScreen>:
    name: 'profile'
    BoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: 'Profile'
            left_action_items: [['menu', lambda x: app.root.toggle_nav_drawer()]]

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 1

            ScrollView:
                MDBoxLayout:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    padding: dp(20)
                    spacing: dp(10)

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)
                        canvas.before:
                            Color:
                                rgba: 0.2, 0.6, 0.8, 1  # Background color for the label
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10,]

                        MDLabel:
                            text: "Forward"
                            theme_text_color: "Primary"
                            halign: "center"
                            font_style: "H6"
                            padding: dp(10)

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: left_wing_checkbox
                            group: 'forward'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Left Wing'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: right_wing_checkbox
                            group: 'forward'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Right Wing'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: center_checkbox
                            group: 'forward'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Center'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)
                        canvas.before:
                            Color:
                                rgba: 0.2, 0.6, 0.8, 1  # Background color for the label
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10,]

                        MDLabel:
                            text: "Defense"
                            theme_text_color: "Primary"
                            halign: "center"
                            font_style: "H6"
                            padding: dp(10)

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: left_defense_checkbox
                            group: 'defense'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Left Defense'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: right_defense_checkbox
                            group: 'defense'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Right Defense'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)
                        canvas.before:
                            Color:
                                rgba: 0.2, 0.6, 0.8, 1  # Background color for the label
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10,]

                        MDLabel:
                            text: "Goalie"
                            theme_text_color: "Primary"
                            halign: "center"
                            font_style: "H6"
                            padding: dp(10)

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: goalie_checkbox
                            group: 'goalie'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Goalie'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)
                        canvas.before:
                            Color:
                                rgba: 0.2, 0.6, 0.8, 1  # Background color for the label
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10,]

                        MDLabel:
                            text: "Shooting Hand"
                            theme_text_color: "Primary"
                            halign: "center"
                            font_style: "H6"
                            padding: dp(10)

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: left_hand_checkbox
                            group: 'shooting_hand'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Left Hand'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

                    MDBoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: self.minimum_height
                        padding: dp(10)
                        spacing: dp(10)

                        MDCheckbox:
                            id: right_hand_checkbox
                            group: 'shooting_hand'
                            size_hint: None, None
                            size: dp(48), dp(48)
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            on_active: root.save_user_profile()
                        MDLabel:
                            text: 'Right Hand'
                            valign: 'middle'
                            size_hint_y: None
                            height: self.texture_size[1]

            Widget:
                size_hint_y: None
                height: dp(10)

            MDRaisedButton:
                text: 'NEXT'
                size_hint_x: 1
                size_hint_y: None
                height: dp(56)
                pos_hint: {'x': 0, 'y': 0}
                on_release: root.go_to_next_screen()
