<SettingsRightNavigationDrawer>:
    orientation: 'vertical'  # Set the orientation to vertical
    padding: '8dp'  # Set the padding
    spacing: '8dp'  # Set the spacing
    canvas.before:
        Color:
            rgba: 0.1, 0.1, 0.1, 1  # Set the background color to darker shade
        Rectangle:
            pos: self.pos  # Set the position
            size: self.size  # Set the size

    AnchorLayout:
        anchor_x: 'left'  # Anchor the layout to the left
        size_hint_y: None  # No size hint for y dimension
        height: avatar.height  # Set the height based on avatar

        Image:
            id: avatar  # Set the ID for the avatar image
            size_hint: None, None  # No size hint
            size: '56dp', '56dp'  # Set the size
            source: 'kivymd_logo.png'  # Set the source image

    MDLabel:
        text: 'KivyMD library'  # Set the text
        font_style: 'Button'  # Set the font style
        theme_text_color: 'Custom'  # Use custom text color
        text_color: 1, 1, 1, 1  # Set the text color to white
        size_hint_y: None  # No size hint for y dimension
        height: self.texture_size[1]  # Set the height based on the texture size

    MDLabel:
        text: 'kivydevelopment@gmail.com'  # Set the text
        font_style: 'Caption'  # Set the font style
        theme_text_color: 'Custom'  # Use custom text color
        text_color: 1, 1, 1, 1  # Set the text color to white
        size_hint_y: None  # No size hint for y dimension
        height: self.texture_size[1]  # Set the height based on the texture size

    ScrollView:
        MDList:
            OneLineIconListItem:
                text: "Screen 1"
                theme_text_color: 'Custom'  # Use custom text color
                text_color: 1, 1, 1, 1  # Set the text color to white
                on_release:
                    root.nav_drawer.set_state("close")  # Close the drawer on release
                    root.screen_manager.current = 'screen1'  # Switch to screen1
            OneLineIconListItem:
                text: "Screen 2"
                theme_text_color: 'Custom'  # Use custom text color
                text_color: 1, 1, 1, 1  # Set the text color to white
                on_release:
                    root.nav_drawer.set_state("close")  # Close the drawer on release
                    root.screen_manager.current = 'screen2'  # Switch to screen2
