<Screen2>:
    name: 'screen2'
    BoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Screen 2"
            left_action_items: [["menu", lambda x: app.root.ids.nav_drawer.set_state("open")]]
            right_action_items: [["menu", lambda x: app.root.ids.right_nav_drawer.set_state("open")]]
        MDLabel:
            text: "Settings Screen 2"
            halign: 'center'
        MDRaisedButton:
            text: "Go to Screen 1"
            pos_hint: {"center_x": .5}
            on_release: root.manager.current = 'screen1'
